# Config name
name: ''

# Augmentations
extension: '.png'
skip_gt: null
augmentations:
  rotate: [45, 90, 135, 180, 225, 270, 315]
  # vertical and horizontal flipping
  flip: [0, 1]
  pixel_transform:
    contrast: [0.5, 1.5]
    brightness: [-50, 50]
  gamma_correction: [0.6, 0.8, 1.2, 1.4]
#  crop_resize:
#    x_start: 50
#    y_start: 50
#    x_end: 350
#    y_end: 350

# Basis data paths
base_train_data: "data/training/images/"
base_gt_data: "data/training/groundtruth/"
test_data: "data/test_set_images/"

# Augmented data paths
train_data: "data/training/images_augment_4/"
gt_data: "data/training/groundtruth_augment_4/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"

# Comments:
# Config file for augmenting data