# This is the first experiment configuration

# Dataset type
dataset: 'basic'

# Model parameters
model: 'unet'
downscale_factor: 0.5
channels: 3
classes: 2

# Training parameters
epochs: 5
batch_size: 2
num_workers: 4
learning_rate: 0.0001
train_data_ratio: 0.8

# Data paths
train_data: "data/training/images/"
gt_data: "data/training/groundtruth/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"