# DO NOT CHANGE THIS

# Config name
name: ''

# Dataset type
dataset: 'basic'
augmentation_type: 'augment_1'

# Weights pretraining (path)
pretrain: 'pretrained_weights/vgg13_bn-abd245e5.pth'

# Proccessing thresholds
gt_thresh: 0.2
foreground_thresh: 0.25

# Model parameters
model: 'unet'
dropout: False
channels: 3
classes: 2
# resize predicted test image in order to fit the original test image
resize_test: True
# padding size used for padding training image in order to have same dimension with test image (int, 104)
pad_size: null

# Training parameters
epochs: 100
batch_size: 2
num_workers: 2
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2
loss_type: 'cross_entropy'

# Data paths
train_data: "data/training/images_augment_1/"
gt_data: "data/training/groundtruth_augment_1/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"


# Comments:
# Added augmentations and increased epochs: score 90.81, submission score nan, TEST SCORE 83.3 !!! -> OVERFITTING