# DO NOT CHANGE THIS

# Config name
name: ''

# Dataset type
dataset: 'basic'
augmentation_type: 'augment_1'

# Weights pretraining (path)
pretrain: 'pretrained_weights/vgg13_bn-abd245e5.pth'

# Proccessing thresholds
gt_thresh: 0.2
foreground_thresh: 0.25

# Model parameters
model: 'unet'
dropout: True
channels: 3
classes: 2
# resize predicted test image in order to fit the original test image (bool)
resize_test: False
# Splir image in 4x400x400 patches(bool)
predict_patches: True
# Way of combining patches - max or avg
patch_combine: 'avg'
# padding size used for padding training image in order to have same dimension with test image (int, 104)
pad_size: null


# Training parameters
epochs: 50
batch_size: 2
num_workers: 2
# rmsprop or adam
optim_type: 'rmsprop'
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2
loss_type: 'cross_entropy'

# Test time augmentations
test_time_aug: False

# Data paths
train_data: "data/training/images_augment_1/"
gt_data: "data/training/groundtruth_augment_1/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"


# Comments:
# Using 4 patches of 400x400 and average them : TEST SCORE 91
# Using 4 patches of 400x400 and max them : TEST SCORE 90.9

# FGR THRESH
# 0.15: 89.4
# 0.20: 90.5
# 0.25: 91 accuracy is 95.1
# 0.30: 91 accuracy is 95.2
# 0.35: 90.2

# WITH MORPH OPEN - also 91
# TEST TIME AUG - 91.2