# Config name
name: ''

# Dataset type
dataset: 'basic'
augmentation_type: ''

# Weights pretraining
pretrain: null

# Proccessing thresholds
gt_thresh: 0.2
foreground_thresh: 0.25

# Model parameters
model: 'unet'
dropout: False
channels: 3
classes: 2
# resize predicted test image in order to fit the original test image
resize_test: True
# padding size used for padding training image in order to have same dimension with test image
pad_size: null

# Training parameters
epochs: 10
batch_size: 2
num_workers: 2
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2
loss_type: 'focal'
focal_gamma: 2
focal_alpha: 0.25

# Data paths
train_data: "data/training/images/"
gt_data: "data/training/groundtruth/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"


# Comments:

# Colab max score:
  # without pip libraries: 0.7025
  # with my pip libraries: 0.7423 !!!!!!!!!!!
  # + with batch_size 8: 0.6990
  # + with epochs 23/40: 0.7681 - NOT FINISHED (KICKED ME OUT)

# Local max score: 0.7477 - submission score is 0.8054 -