# DO NOT CHANGE THIS

# Config name
name: ''

# Dataset type
dataset: 'basic'
augmentation_type: 'augment_3'

# Weights pretraining (path)
pretrain: 'pretrained_weights/vgg13_bn-abd245e5.pth'

# Proccessing thresholds
gt_thresh: 0.2
foreground_thresh: 0.25

# Model parameters
model: 'unet'
dropout: True
channels: 3
classes: 2
# resize predicted test image in order to fit the original test image (bool)
resize_test: False
# Splir image in 4x400x400 patches(bool)
predict_patches: True
# Way of combining patches - max or avg
patch_combine: 'avg'
# padding size used for padding training image in order to have same dimension with test image (int, 104)
pad_size: null


# Training parameters
epochs: 100
batch_size: 2
num_workers: 2
# rmsprop or adam
optim_type: 'rmsprop'
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2
loss_type: 'cross_entropy'

# Test time augmentations
test_time_aug: False

# Data paths
train_data: "data/training/images_augment_3/"
gt_data: "data/training/groundtruth_augment_3/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"


# Comments:
# Using augmentation_3 (100 ep, the rest as 15): score is , submission score is , TEST SCORE IS !!!!!