# Config name
name: ''

# Dataset type
dataset: 'basic'
augmentation_type: ''

# Proccessing thresholds
gt_thresh: 0.2
foreground_thresh: 0.25

# Model parameters
model: 'unet'
resize_test: True
channels: 3
classes: 2

# Training parameters
epochs: 10
batch_size: 2
num_workers: 2
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2
loss_type: 'cross_entropy_dice'

# Data paths
train_data: "data/training/images/"
gt_data: "data/training/groundtruth/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"

# Visualization folder
viz_path: "visualizations/"


# Comments:
# DO NOT CHANGE THIS - USED FOR GENERATING submission_experiment_2.csv !
# It seems that gt_thresh: 0.2 is a good threshold , since best results between experiment 1, 2 and 3.