# This is the first experiment configuration
name: ''

# Dataset type
dataset: 'basic'

# GT threshold
gt_thresh: 0.2

# Model parameters
model: 'unet'
downscale_factor: 0.5
channels: 3
classes: 2

# Training parameters
epochs: 10
batch_size: 2
num_workers: 4
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00000001
train_data_ratio: 0.8
save_checkpoints_interval: 5
patience: 2

# Data paths
train_data: "data/training/images/"
gt_data: "data/training/groundtruth/"
test_data: "data/test_set_images/"

# Submissions folder
output_path: "results/"

# Checkpoints folder
checkpoints_path: "checkpoints/"

# Logs folder
log_dir_path: "logs/"